project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Lab.qmd
        text: Labs
      - href: Presentation.qmd
        text: Presentation
      - href: Project.qmd
        text: Project  

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual



